### ISSUE TITLE
The argument 'filename' must be a file URL object

### ISSUE THREAD

**Issue by Morcatko** [atamano/jsonpathly#6]
Hello I am trying to use your library in a nextjs project (in a server code) and it fails with following error:

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///Users/antoine/git/jsonpathly/node_modules/antlr4/dist/antlr4.node.mjs'
```

The stacktrace is a bit mess as nextjs adds a lot of its own functionality. Anyway the same happens when I try to run just unit tests with `vitest`

If you look into `jsonpathly/dist/index.node.mjs` and `index.node.cjs` and search for `antlr4/dist` you will find this code
```
...
const Oe=(0,t.createRequire)("file:///Users/antoine/git/jsonpathly/node_modules/antlr4/dist/antlr4.node.mjs")("fs")
...
```

I don't know much about javascript modules and webpack so I have really not idea how to fix/workaround it

Thanks for this library and for your help

**Comment by atamano** [comment]
This seems to be an antlr4 issue, I will have a look

**Comment by atamano** [comment]
This does seem to solve the issue. Could you please open a PR with your fix? I tested it manually on web and Node/CJS, and it worked. I will add automated tests before releasing a new version.

**Comment by Morcatko** [comment]
Here it is: https://github.com/atamano/jsonpathly/pull/7

**Comment by atamano** [comment]
Thank you !

**Comment by dexwest** [comment]
How can we get this fix published?
